using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414
namespace daBizmate
{

	[Preserve]
	public partial class E_test1 : BGEntity
	{
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5341872963209070777UL,10297050517792251835UL), () => _metaDefault = null));
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public static int CountEntities => MetaDefault.CountEntities;
		public System.String f_name
		{
			get => _f_name[Index];
			set => _f_name[Index] = value;
		}
		public System.Int32 f_test2
		{
			get => _f_test2[Index];
			set => _f_test2.SetValue(this, value);
		}
		public System.Int32 f_test3
		{
			get => _f_test3[Index];
			set => _f_test3.SetValue(this, value);
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4699585078509955893UL, 16360169007455962300UL), () => _ufle12jhs77_f_name = null));
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_test2;
		public static BansheeGz.BGDatabase.BGFieldInt _f_test2 => _ufle12jhs77_f_test2 ?? (_ufle12jhs77_f_test2 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5152037172268570821UL, 12172304789506836887UL), () => _ufle12jhs77_f_test2 = null));
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_test3;
		public static BansheeGz.BGDatabase.BGFieldInt _f_test3 => _ufle12jhs77_f_test3 ?? (_ufle12jhs77_f_test3 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4823197293440044284UL, 9674219886864195515UL), () => _ufle12jhs77_f_test3 = null));
		private E_test1() : base(MetaDefault) {}
		private E_test1(BGId id) : base(MetaDefault, id) {}
		private E_test1(BGMetaEntity meta) : base(meta) {}
		private E_test1(BGMetaEntity meta, BGId id) : base(meta, id) {}
		public static E_test1 FindEntity(Predicate<E_test1> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
		public static List<E_test1> FindEntities(Predicate<E_test1> filter, List<E_test1> result=null, Comparison<E_test1> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
		public static void ForEachEntity(Action<E_test1> action, Predicate<E_test1> filter=null, Comparison<E_test1> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
		public static E_test1 GetEntity(BGId entityId) => (E_test1) MetaDefault.GetEntity(entityId);
		public static E_test1 GetEntity(int index) => (E_test1) MetaDefault[index];
		public static E_test1 GetEntity(string entityName) => (E_test1) MetaDefault.GetEntity(entityName);
		public static E_test1 NewEntity() => (E_test1) MetaDefault.NewEntity();
		public static E_test1 NewEntity(BGId entityId) => (E_test1) MetaDefault.NewEntity(entityId);
		public static E_test1 NewEntity(Action<E_test1> callback) => (E_test1) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((E_test1)entity)));

		[Preserve]
		public class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta) => new E_test1(meta);
			public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new E_test1(meta, id);
		}

		public static class __Names
		{
			public const string Meta = "test1";
			public const string name = "name";
			public const string test2 = "test2";
			public const string test3 = "test3";
		}
	}

	[Preserve]
	public partial class E_test4 : BGEntity
	{
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4916650461417586208UL,10915596894192320419UL), () => _metaDefault = null));
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public static int CountEntities => MetaDefault.CountEntities;
		public System.String f_name
		{
			get => _f_name[Index];
			set => _f_name[Index] = value;
		}
		public System.String f_test3
		{
			get => _f_test3[Index];
			set => _f_test3[Index] = value;
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5100817670900262233UL, 13730673973057063046UL), () => _ufle12jhs77_f_name = null));
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_test3;
		public static BansheeGz.BGDatabase.BGFieldString _f_test3 => _ufle12jhs77_f_test3 ?? (_ufle12jhs77_f_test3 = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5622662325523477667UL, 2033418782180317103UL), () => _ufle12jhs77_f_test3 = null));
		private E_test4() : base(MetaDefault) {}
		private E_test4(BGId id) : base(MetaDefault, id) {}
		private E_test4(BGMetaEntity meta) : base(meta) {}
		private E_test4(BGMetaEntity meta, BGId id) : base(meta, id) {}
		public static E_test4 FindEntity(Predicate<E_test4> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
		public static List<E_test4> FindEntities(Predicate<E_test4> filter, List<E_test4> result=null, Comparison<E_test4> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
		public static void ForEachEntity(Action<E_test4> action, Predicate<E_test4> filter=null, Comparison<E_test4> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
		public static E_test4 GetEntity(BGId entityId) => (E_test4) MetaDefault.GetEntity(entityId);
		public static E_test4 GetEntity(int index) => (E_test4) MetaDefault[index];
		public static E_test4 GetEntity(string entityName) => (E_test4) MetaDefault.GetEntity(entityName);
		public static E_test4 NewEntity() => (E_test4) MetaDefault.NewEntity();
		public static E_test4 NewEntity(BGId entityId) => (E_test4) MetaDefault.NewEntity(entityId);
		public static E_test4 NewEntity(Action<E_test4> callback) => (E_test4) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((E_test4)entity)));

		[Preserve]
		public class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta) => new E_test4(meta);
			public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new E_test4(meta, id);
		}

		public static class __Names
		{
			public const string Meta = "test4";
			public const string name = "name";
			public const string test3 = "test3";
		}
	}

	[Preserve]
	public partial class E_User : BGEntity
	{
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5441921846869725549UL,18167309817583276956UL), () => _metaDefault = null));
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public static int CountEntities => MetaDefault.CountEntities;
		public System.String f_name
		{
			get => _f_name[Index];
			set => _f_name[Index] = value;
		}
		public System.String f_Code
		{
			get => _f_Code[Index];
			set => _f_Code[Index] = value;
		}
		public System.Int32 f_Status
		{
			get => _f_Status[Index];
			set => _f_Status.SetValue(this, value);
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4618010221164483866UL, 1003446012388372364UL), () => _ufle12jhs77_f_name = null));
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Code;
		public static BansheeGz.BGDatabase.BGFieldString _f_Code => _ufle12jhs77_f_Code ?? (_ufle12jhs77_f_Code = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5701628194753094171UL, 15939167648174110394UL), () => _ufle12jhs77_f_Code = null));
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_Status;
		public static BansheeGz.BGDatabase.BGFieldInt _f_Status => _ufle12jhs77_f_Status ?? (_ufle12jhs77_f_Status = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5037230406205795585UL, 12441707818700282046UL), () => _ufle12jhs77_f_Status = null));
		private E_User() : base(MetaDefault) {}
		private E_User(BGId id) : base(MetaDefault, id) {}
		private E_User(BGMetaEntity meta) : base(meta) {}
		private E_User(BGMetaEntity meta, BGId id) : base(meta, id) {}
		public static E_User FindEntity(Predicate<E_User> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
		public static List<E_User> FindEntities(Predicate<E_User> filter, List<E_User> result=null, Comparison<E_User> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
		public static void ForEachEntity(Action<E_User> action, Predicate<E_User> filter=null, Comparison<E_User> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
		public static E_User GetEntity(BGId entityId) => (E_User) MetaDefault.GetEntity(entityId);
		public static E_User GetEntity(int index) => (E_User) MetaDefault[index];
		public static E_User GetEntity(string entityName) => (E_User) MetaDefault.GetEntity(entityName);
		public static E_User NewEntity() => (E_User) MetaDefault.NewEntity();
		public static E_User NewEntity(BGId entityId) => (E_User) MetaDefault.NewEntity(entityId);
		public static E_User NewEntity(Action<E_User> callback) => (E_User) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((E_User)entity)));

		[Preserve]
		public class Factory : BGEntity.EntityFactory
		{
			public BGEntity NewEntity(BGMetaEntity meta) => new E_User(meta);
			public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new E_User(meta, id);
		}

		public static class __Names
		{
			public const string Meta = "User";
			public const string name = "name";
			public const string Code = "Code";
			public const string Status = "Status";
		}
	}
}
#pragma warning restore 414
